# A Supabase project config file
# See: https://supabase.com/docs/guides/cli/local-development

# Project configuration
project_id = "pqcgagpijzghdedxwemi"  # Your project ID from Supabase dashboard

# API Configuration
[api]
# Enable the API service
enabled = true
# Port for the API gateway
port = 54321
# Allowed schemas for API access
schemas = ["public", "storage", "auth"]
# Extra schemas to include in the search path
extra_search_path = ["public", "extensions"]
# Maximum number of rows returned from a view, table, or stored procedure
max_rows = 1000

# Database Configuration
[db]
# Port for the database server
port = 54322
# Major version of Postgres
major_version = 15
# Port for the shadow database (used for migrations)
shadow_port = 54320

# Studio Configuration (Supabase Dashboard)
[studio]
# Enable Studio service
enabled = true
# Port for Studio
port = 54323
# API URL for Studio to connect to
api_url = "http://localhost:54321"

# Authentication Configuration
[auth]
# Enable the Auth service
enabled = true
# Site URL for authentication callbacks
site_url = "http://localhost:3000"
# Additional redirect URLs
additional_redirect_urls = ["https://localhost:3000"]
# JWT token expiry
jwt_expiry = 3600
# Enable signups
enable_signup = true

# Storage Configuration
[storage]
# Enable the Storage service
enabled = true
